### ISSUE TITLE
Read Write operation is not working

### ISSUE THREAD

**Issue by 27bharath** [sscarduzio/elasticsearch-readonlyrest-plugin#244]
Hi,

Below is my configuration in my elastic search nodes and below issues am facing.

1. Asks for username and password window for many times almost more than 10 times 
2. User can able to delete index, dashboards, visulization even i have mentioned in the elasticsearch.yml file as **kibana_access: rw**.

**ElasticSearch version** : 5.2.0
**Readonlyrest vesrion** : 5.2.0

**elastisearch.yml**

```yml
 readonlyrest:
   enable: true
   response_if_req_forbidden: Access Denied

   access_control_rules:
    - name: "Logstash Authentication"
      auth_key: blah:blah
      type: allow
      actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/","indices:data/write/","indices:admin/template/","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "Kibana Authentication"
      auth_key: blah:blah
      verbosity: error
      type: allow

    - name: "Read Write For All Users"
      type: allow
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
      ldap_authentication:
         name: "ldap"
         cache_ttl_in_sec: 60

    - name: "Admin Access for a Group"
      type: allow
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
      ldap_auth:
         name: "ldap"
         groups: ["AdminGroup"]
         cache_ttl_in_sec: 60

   ldaps:
    - name: ldap
      host: "hostname.com"
      port: 8080
      ssl_enabled: true 
      ssl_trust_all_certs: true
      search_user_base_DN: "ou=People,ou=PeopleSearch,dc=my,dc=com"
      search_groups_base_DN: "ou=Autogroups,ou=PeopleSearch,dc=my, dc=com"
      user_id_attribute: "uid"
      unique_member_attribute: "uniqueMember"
      connection_pool_size: 10
      connection_timeout_in_sec: 10
      request_timeout_in_sec: 10
      cache_ttl_in_sec: 60*
```
#####################################################################
In kibana UI, 

I have created index name as **applogs** in Kibada -> Index Patterns

**Logstash : myconfig.conf**
```
output {
    elasticsearch {
        hosts => ["es-client1.com:9200","es-client2.com:9200","es-client3.com:9200"]
        index => "logstash-prodnum-uat-applogs-%{+YYYY.MM.dd}-1"
        flush_size => 15000
        user => logstash
        password => logstash
    }
}
```
Please help me on this

**Comment by sscarduzio** [comment]
You mentioned your user is able to delete stuff: what user credentials are your using?

**Comment by 27bharath** [comment]
you can see i have mentioned only authentication part for read write operation. My colleagues use their own credentials (username and password) to authenticate through LDAP

    - name: "Read Write For All Users"
      type: allow
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
      ldap_authentication:
         name: "ldap"
         cache_ttl_in_sec: 60

But if i install readonlyrest 5.3 version in my elastic search they cant do delete operation for the same configuration mentioned above . Is this resolved in higher versions ?

**Comment by sscarduzio** [comment]
So let me to recap your test:

### TEST
1. Try to delete an index as a valid LDAP user, which **does not belong** to "AdminGroup" LDAP group.
2. You expect the rule "Read Write For All Users" not to match because deleting is not a valid Kibana RW operation.
3. You expect the rule "Admin Access for a Group" not to match because the user **does not belong** to LDAP group "AdminGroup".

### RESULT
4. In ES 5.2.0 **BUG**:  this request is accepted (please check the ES logs to see **what rule** is allowing the request in).
5. In ES 5.3.x **OK**: the request is rejected

You didn't tell me the version of the plugin, just the version of ES. It should be something like this: `v1.16.6_es5.2.2` please see what you got installed.

> Is this resolved in higher versions ?
Higher version of the plugin? Yes.

**Comment by TRISAF** [comment]
Not resolved Simon,
We are not talking about delete action. 
We are using the most high version of RoR , doenloaded today for es 5.4.0. 
We are talking about viewing data ( indexes) about indexes not liste in "indeces" list of that passed to es from user to kibana whitelist. 

Inviato da iPhone

**Comment by sscarduzio** [comment]
Sorry I meant "yes it may be resolved" (since at that point I didn't know what **plugin** version you are using).

Do you have any logs to show? I was thinking this might be related to #251

**Comment by 27bharath** [comment]
Elastic search 5.5 got released, when we can expect RoR 5.5 version ?
And in **indices : [".kibana", ".kibana-devnull"]** if we mention **kibana_access: rw** what is the difference in .kibana and .kibana-devnull and what all will have access to read and what all will have access to write operation.

Can you please elaborate the difference

**Comment by sscarduzio** [comment]
Yes, 5.5.0 is already working. Will release soon with 1.16.8 and a few important bug fixes.
`.kibana-devnull` is a fake index old versions of Kibana used to query. It's legacy, you can remove it if you use so recent versions as (at least) 5.3.x or greater.

Ref. about `.kibana-devnull` https://github.com/elastic/kibana/issues/7283

**Comment by 27bharath** [comment]
I have installed below versions and i have same configuration mentioned in the above 1st Comment.

Elastic Search:  5.5.0v
RoR : readonlyrest-1.16.8_es5.5.0 

But still the RW operation is not working the user have access to delete the dashboard, visualization, indices as per the your above comments you said the bug is fixed in higher versions. 


Please comment out for my below individual points : 

1. Please list out the features **kibana_access: rw** (Can you please explain what is the use of kibana_access: rw, what i can restrict if i use this option)
2. Please suggest me what configuration is required if i want to restrict users to dont have a permission for delete operations like ( Delete Visualization , Delete dashboards, Delete Indices)
3. Please suggest me what configuration is required if i want to restrict users to dont have a permission for edit operations like ( Update other user created Visualization , Update other user created dashboards, Update other user created Indices)

**Comment by sscarduzio** [comment]
Can you start from this canonical example? Because with this I just tested it works.

```yaml
readonlyrest:
    access_control_rules:

    - name: "::LOGSTASH::"
      auth_key: logstash:logstash
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana

    - name: "::RO::"
      auth_key: ro:dev
      kibana_access: ro
      indices: [ ".kibana", ".kibana-devnull", "logstash-*"]

    - name: "::RW::"
      auth_key: rw:dev
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-*"]

```

**Comment by 27bharath** [comment]
Yes i can do delete operation for  **kibana_access: rw**. 

 readonlyrest:
   enable: true
   response_if_req_forbidden: Access Denied
   
   access_control_rules:
    - name: "Logstash Authentication"
      auth_key: logstash:logstash
      type: allow
      actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "ElasticSearch API and Kibana Authentication"
      auth_key: esadmin:esadmin
      verbosity: error 
      type: allow

    - name: "Read Write For All Fidelity Users"
      kibana_access: rw
      indices: [".kibana", "logstash-*"]
      auth_key: apps:bharath
      type: allow

**Comment by sscarduzio** [comment]
So I tried again with my proposed "canonical" configuration.
```yaml
readonlyrest:
    access_control_rules:

    - name: "::LOGSTASH::"
      auth_key: logstash:logstash
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana

    - name: "::RO::"
      auth_key: ro:dev
      kibana_access: ro
      indices: [ ".kibana", ".kibana-devnull", "logstash-*"]

    - name: "::RW::"
      auth_key: rw:dev
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
```
I created a .kibana index, and then tried the following manual tests:

## Get .kibana documents as "rw": OK ✅ 
```
$ curl -vvv -urw:dev  localhost:9200/.kibana
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* Server auth using Basic with user 'rw'
> GET /.kibana HTTP/1.1
> Host: localhost:9200
> Authorization: Basic cnc6ZGV2
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-ror-kiban_access: RW
< x-ror-kibana_index: .kibana
< content-type: application/json; charset=UTF-8
< content-length: 2539
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{".kibana":{"aliases":{},"mappings":{"url":{"dynamic":"strict","properties":{"accessCount":{"type":"long"},"accessDate":{"type":"date"},"createDate":{"type":"date"},"url":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":2048}}}}},"timelion-sheet":{"dynamic":"strict","properties":{"description":{"type":"text"},"hits":{"type":"integer"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"timelion_chart_height":{"type":"integer"},"timelion_columns":{"type":"integer"},"timelion_interval":{"type":"keyword"},"timelion_other_interval":{"type":"keyword"},"timelion_rows":{"type":"integer"},"timelion_sheet":{"type":"text"},"title":{"type":"text"},"version":{"type":"integer"}}},"dashboard":{"dynamic":"strict","properties":{"description":{"type":"text"},"hits":{"type":"integer"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"optionsJSON":{"type":"text"},"panelsJSON":{"type":"text"},"refreshInterval":{"properties":{"display":{"type":"keyword"},"pause":{"type":"boolean"},"section":{"type":"integer"},"value":{"type":"integer"}}},"timeFrom":{"type":"keyword"},"timeRestore":{"type":"boolean"},"timeTo":{"type":"keyword"},"title":{"type":"text"},"uiStateJSON":{"type":"text"},"version":{"type":"integer"}}},"index-pattern":{"dynamic":"strict","properties":{"fieldFormatMap":{"type":"text"},"fields":{"type":"text"},"intervalName":{"type":"keyword"},"notExpandable":{"type":"boolean"},"sourceFilters":{"type":"text"},"timeFieldName":{"type":"keyword"},"title":{"type":"text"}}},"server":{"dynamic":"strict","properties":{"uuid":{"type":"keyword"}}},"_default_":{"dynamic":"strict"},"config":{"dynamic":"true","properties":{"buildNum":{"type":"keyword"}}},"visualization":{"dynamic":"strict","properties":{"description":{"type":"text"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"savedSearchId":{"type":"keyword"},"title":{"type":"text"},"uiStateJSON":{"type":"text"},"version":{"type":"integer"},"visState":{"type":"text"}}},"search":{"dynamic":"strict","properties":{"columns":{"type":"keyword"},"description":{"type":"text"},"hits":{"type":"integer"},"kibanaSavedObjectMeta":{"properties":{"searchSourceJSON":{"type":"text"}}},"sort":{"type":"keyword"},"title":{"type":"text"},"version":{"type":"integer"}}}},"settings":{"index":{"number_of_shards":"1","provided_name":".kibana","mapper":{"dynamic":"false"},"creation_date":"1500648265149","number_of_replicas":"1","uuid":"Z4mJZub3R52ZURRha5o9TQ","version":{"created":"5050099"}}}}}
```


## Delete index logged in as "rw": Unauthorized ✅ 
```
$ curl -vvv -urw:dev  -XDELETE localhost:9200/.kibana
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* Server auth using Basic with user 'rw'
> DELETE /.kibana HTTP/1.1
> Host: localhost:9200
> Authorization: Basic cnc6ZGV2
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic
< content-type: text/plain; charset=UTF-8
< content-length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

## Bulk delete all items in `.kibana `logged in as "rw": Unauthorized ✅ 
```
$ curl -vvv -urw:dev -XDELETE 'http://localhost:9200/_query' -d '{"query": {"bool": { "must": [{"match_all": {} } ] } } }'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
* Server auth using Basic with user 'rw'
> DELETE /_query HTTP/1.1
> Host: localhost:9200
> Authorization: Basic cnc6ZGV2
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 56
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 56 out of 56 bytes
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic
< Warning: 299 Elasticsearch-5.5.0-260387d "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Fri, 21 Jul 2017 14:52:40 GMT"
< content-type: text/plain; charset=UTF-8
< content-length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

I'm not sure why I can't reproduce this. Any hint?
